# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f2b76af27177ee172fb3288b2a335bf7cf86ee4d34ffa478d3dce9075c3dff0bde57356dbbb5dc27f10640eb3810e7fcc3c2215624afd6bf635daafd442ec9c0

test:
  secret_key_base: ecc3aa1de55ce2d12ad1f6dac3ff51954c80f5cf5cdaeb9d6682d660806fcaae60418d193456344432a8cf6a320dcc6043f8c1bb5ed8d137d3c811b928646b85

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
